baseURL = 'https://amksde.github.io'
languageCode = 'en-us'
title = 'Aman Kumar'

[params]
  description = "A minimalist personal website"
  author = "Aman Kumar"

# Enable math rendering
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$'], ['\\[', '\\]']]
          inline = [['$', '$'], ['\\(', '\\)']]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Recommendations"
    url = "/recommendations/"
    weight = 3
  [[menu.main]]
    name = "Bookshelf"
    url = "/bookshelf/"
    weight = 4
  [[menu.main]]
    name = "Dotfiles"
    url = "/dotfiles/"
    weight = 5
  [[menu.main]]
    name = "Playlist"
    url = "/playlist/"
    weight = 6
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 7
  
[frontmatter]
  lastmod = ["lastmod", ":git", "publishDate"]